# Generated by Django 5.1.3 on 2024-11-08 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='frist_name',
            new_name='first_name',
        ),
    ]
